
export function loadLists() {
  return [
    {
      title: 'Disciplinas',
      creatable: true,
      cards: [
        {
          id: "1",
          teacher: 'joao',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },
        {
          id: "2",
          teacher: 'pedro',
          content: 'Lógica de programação',
          labels: ['#7159c1'],
          user: ' ',
        },
        {
          id: "3",
          teacher: 'thiago',
          content: 'banco de dados',
          labels: ['#7159c1'],
          user: ' ',
        },
        {
          id: "4",
          teacher: 'felipe',
          content: 'calculo I"',
          labels: ['#54e1f7'],
          user: ' ',
        },
        {
          id: "5",
          teacher: 'rafael',
          content: 'Calculo II',
          labels: ['#54e1f7'],
          user: ' ',
        },
      ],
    },
    {
      title: 'horarios',
      creatable: true,
      horary: true,
      bloco_id: "",
      turno:'vespertino',
      cards: [
        {
          id: 1,
          horario: '13:00 - 13:50',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },
        {
          id:2 ,
          horario: '12:50',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },        {
          id: 3,
          horario: '15:40',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },        {
          id: 4,
          horario: '16:30',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },        {
          id: 5,
          horario: '17:20',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },        {
          id: 6,
          horario: '18:10',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: ' ',
        },

      ],
    },
    {
      title: 'Segunda-Feira',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "11",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "12",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "13",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "14",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "15",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "16",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
    {
      title: 'Terça-Feira',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "1",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "2",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "3",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "4",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "5",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "6",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
    {
      title: 'Quarta-Feira',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "1",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "2",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "3",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "4",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "5",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "6",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
    {
      title: 'Quinta-Feira',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "1",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "2",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "3",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "4",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "5",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "6",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
    {
      title: 'Sexta-Feira',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "1",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "2",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "3",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "4",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "5",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "6",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
    {
      title: 'Sábado',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "1",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "2",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "3",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "4",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "5",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "6",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
    {
      title: 'Domingo',
      creatable: false,
      bloco_id: "",
      cards: [
        {
          id: "1",
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: ' ',
        }, {
          id: "2",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "3",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "4",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "5",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        }, {
          id: "6",
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: ' ',
        },
      ],
    },
  ];
}
