
export function loadLists() {
  return [
    {
      title: 'Disciplinas',
      creatable: true,
      cards: [
        {
          id: 1,
          teacher: 'joao',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
        {
          id: 2,
          teacher: 'pedro',
          content: 'Lógica de programação',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
        {
          id: 3,
          teacher: 'thiago',
          content: 'banco de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
        {
          id: 4,
          teacher: 'felipe',
          content: 'calculo I"',
          labels: ['#54e1f7'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
        {
          id: 5,
          teacher: 'rafael',
          content: 'Calculo II',
          labels: ['#54e1f7'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'horarios',
      creatable: true,
      horary: true,
      turno:'vespertino',
      cards: [
        {
          id: 1,
          horario: '13:45',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
        {
          id:2 ,
          horario: '12:50',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },        {
          id: 3,
          horario: '15:40',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },        {
          id: 4,
          horario: '16:30',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },        {
          id: 5,
          horario: '17:20',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },        {
          id: 6,
          horario: '18:10',
          content: 'Estrutura de dados',
          labels: ['#7159c1'],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
        
      ],
    },
    {
      title: 'Segunda-Feira',
      creatable: false,
      cards: [
        {
          id: 11,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 12,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 13,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 14,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 15,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 16,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'Terça-Feira',
      creatable: false,
      cards: [
        {
          id: 1,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 2,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 3,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 4,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 5,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 6,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'Quarta-Feira',
      creatable: false,
      cards: [
        {
          id: 1,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 2,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 3,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 4,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 5,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 6,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'Quinta-Feira',
      creatable: false,
      cards: [
        {
          id: 1,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 2,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 3,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 4,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 5,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 6,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'Sexta-Feira',
      creatable: false,
      cards: [
        {
          id: 1,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 2,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 3,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 4,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 5,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 6,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'Sábado',
      creatable: false,
      done: true,
      cards: [
        {
          id: 1,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 2,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 3,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 4,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 5,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 6,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
    {
      title: 'Domingo',
      creatable: false,
      done: true,
      cards: [
        {
          id: 1,
          teacher: '',
          content: 'horario livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 2,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 3,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 4,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 5,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        }, {
          id: 6,
          teacher: '',
          content: 'Horario Livre',
          labels: [],
          user: 'https://rocketseat-cdn.s3-sa-east-1.amazonaws.com/profile.png',
        },
      ],
    },
  ];
}
